[package]
name         = "url-cleaner"
version      = "0.12.0-beta"
edition      = "2024"
description  = "URL Cleaner's official CLI frontend."
repository   = "https://github.com/Scripter17/url-cleaner"
keywords     = ["url", "url-tracking", "privacy", "url-cleaner"]
categories   = ["command-line-utilities"]
license      = "AGPL-3.0-or-later"
readme       = "README.md"
rust-version = "1.96.1"

[dependencies]
# URL Cleaner.
better-url         = { version = "0.12.0-beta", path = "../better-url", features = ["serde"]}
url-cleaner-engine = { version = "0.12.0-beta", path = "../engine", default-features = false }

# Other.
clap      = { version = "4.6.6" , features = ["derive", "unstable-v5"] }
tokio     = { version = "1.53.1", features = ["sync", "io-util", "io-std", "macros", "rt-multi-thread", "time"] }
bytes     = "1.12.1"
thiserror = "2.0.20"

[features]
default = ["bundled-cleaner"]

bundled-cleaner = [
  "url-cleaner-engine/bundled-cleaner",
  "http",
  "cache"
]

http  = ["url-cleaner-engine/http"]
cache = ["url-cleaner-engine/cache"]

[lints]
workspace = true
