[package]
name         = "url-cleaner-discord"
version      = "0.12.0-beta"
edition      = "2024"
description  = "URL Cleaner's official Discord frontend."
repository   = "https://github.com/Scripter17/url-cleaner"
keywords     = ["url", "url-tracking", "privacy", "url-cleaner"]
categories   = []
license      = "AGPL-3.0-or-later"
readme       = "README.md"
rust-version = "1.96.1"
publish      = false

[dependencies]
# URL Cleaner.
url-cleaner-engine = { version = "0.12.0-beta", path = "../engine", default-features = false }

# Discord.
serenity  = { git = "https://github.com/serenity-rs/serenity", branch = "next" }

# Other.
clap      = { version = "4.6.6" , features = ["derive", "unstable-v5"] }
tokio     = { version = "1.53.1", features = ["rt-multi-thread"      ] }
bytes     = "1.12.1"
regex     = "1.13.1"
thiserror = "2.0.20"

[features]
default = ["bundled-cleaner"]

bundled-cleaner = [
  "url-cleaner-engine/bundled-cleaner",
  "http",
  "cache",
]

http  = ["url-cleaner-engine/http"]
cache = ["url-cleaner-engine/cache"]

[lints]
workspace = true
