// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `cache` table.
    ///
    /// (Automatically generated by Diesel.)
    cache (id) {
        /// The `id` column of the `cache` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Integer,
        /// The `category` column of the `cache` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        category -> Text,
        /// The `key` column of the `cache` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        key -> Text,
        /// The `value` column of the `cache` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        value -> Nullable<Text>,
    }
}
