[package]
name = "adguard-converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
reqwest = "0.11.23"
serde_json = "1.0.108"
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["rt", "macros"] }
url-cleaner = { path = ".." }
