name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: ./tests.sh --only-build

  build_ndf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build_ndf
      run: ./tests.sh --only-build-ndf

  cargo_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: cargo_test
      run: ./tests.sh --only-cargo-test

  order_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test_order
      run: ./tests.sh --only-test-order

  offline_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: offline_tests
      run: ./tests.sh --only-offline-tests

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: clippy
      run: ./tests.sh --only-clippy

  powerset_2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: taiki-e/install-action@cargo-hack
    - name: powerset
      run: ./tests.sh --only-powerset
