name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: rustup update stable && cargo build --verbose

  build_NDF:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build no default features
      run: rustup update stable && cargo build --verbose --no-default-features

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: rustup update stable && cargo test --verbose -- --skip ExpandRedirect

  test_NDF:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests no default features
      run: rustup update stable && cargo test --verbose --no-default-features -- --skip default_config
