name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build.
      run: cargo build

  build no default features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build no default features.
      run: cargo build --no-default-features

  test default config:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - mame: Run the non-network default config tests.
      run: cargo run -- --tests tests.json

  test default features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run cargo test on default features.
      run: cargo test

  test subsets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: taiki-e/install-action@cargo-hack
    - name: Test feature subsets of size 3 and below.
      run: cargo hack test --feature-powerset --depth 3
