name: Workspace Linux

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_dev_DEBUG: 0

jobs:
  versions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Versions
      run: |
        set -euo pipefail
        version_lines=$(grep -PI '^(// @version|url-cleaner.+version|^version)' */Cargo.toml site/src/userscript.js)
        versions=$(echo "$version_lines" | grep -oP '\d[\d.]+(-beta)?')
        if [ $(echo "$versions" | uniq | wc -l) -ne 1 ]; then
          pad_to=$(echo "$version_lines" | grep -oP '^.+?:' | wc -L)
          echo "Version mismatch!"
          echo "$version_lines" | sed -E ":a s/^(.{0,$pad_to}): ?/\1 : /; ta"
          exit 1
        fi

  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Check MSRV consistency'
      run: |
        set -euo pipefail
        [[ "$(cat */Cargo.toml | grep -oP '(?<=^rust-version = \")[\d.]+' | sort -u | wc -l)" == 1 ]]

  fresh_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Check that bundled_cleaner.md is fresh'
      run: |
        set -euo pipefail
        diff <(cargo run --bin urlc-tool -- cleaner doc) bundled_cleaner.md
